# Generated by Django 4.2 on 2023-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="TermsConditions",
            new_name="TermsAndConditions",
        ),
    ]
